project:
  type: website

website:
  title: "Data Science Bytes"
  site-url: https://www.javierorracadeatcu.com
  description: "Javier Orraca-Deatcu's data science website built with R and Quarto"
  open-graph: true
  draft-mode: unlinked
  google-analytics:
    tracking-id: "G-9L6JEKD131"
    anonymize-ip: true
  cookie-consent: true
  twitter-card: 
    image: images/Javier_Profile.jpg
    card-style: summary_large_image
    creator: "@JavierOrraca"
  navbar:
    right:
      - icon: rss
        href: blog.xml
      - icon: linkedin
        href: https://www.linkedin.com/in/orraca
        target: _blank
      - text: "{{< iconify fa6-brands bluesky >}}"
        href: https://bsky.app/profile/javierorracadeatcu.bsky.social
        target: _blank
      - icon: twitter-x
        href: https://x.com/JavierOrraca
        target: _blank
      - icon: spotify
        href: https://open.spotify.com/show/64UpJwByrdsrLSYObuEeHx?si=uZChaWIhSxukmDQbvPm4Uw
        target: _blank
      - icon: github
        href: https://github.com/JavOrraca
        target: _blank
      - icon: stack-overflow
        href: https://stackoverflow.com/users/17282384/javier-orraca-deatcu
        target: _blank
      - text: Blog
        href: blog.qmd
      - text: Python & R
        href: resources.qmd
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap

webr: 
  show-startup-message: false
  show-header-message: false
  channel-type: 'post-message'