project:
  type: website

website:
  title: "Data Science Bytes"
  site-url: https://www.javierorracadeatcu.com
  description: "Javier Orraca-Deatcu's data science website built with R and Quarto"
  open-graph: true
  google-analytics:
    tracking-id: "387217041"
    anonymize-ip: true
  cookie-consent: true
  twitter-card: 
    image: images/Javier_Profile.jpg
    card-style: summary_large_image
    creator: "@JavierOrraca"
  navbar:
    right:
      - icon: rss
        href: blog.xml
      - icon: linkedin
        href: https://www.linkedin.com/in/orraca
        target: _blank
      - icon: twitter
        href: https://twitter.com/JavierOrraca
        target: _blank
      - icon: spotify
        href: https://open.spotify.com/show/64UpJwByrdsrLSYObuEeHx?si=uZChaWIhSxukmDQbvPm4Uw
        target: _blank
      - icon: github
        href: https://github.com/JavOrraca
        target: _blank
      - icon: stack-overflow
        href: https://stackoverflow.com/users/17282384/javier-orraca-deatcu
        target: _blank
      - text: Blog
        href: blog.qmd
      - text: Resources
        menu:
          - text: "Javi's Resources"
            href: resources.qmd
          - text: R for Data Science
            href: https://r4ds.hadley.nz/
            target: _blank
          - text: Tidyverse
            href: https://www.tidyverse.org/
            target: _blank
          - text: Tidymodels
            href: https://www.tidymodels.org/
            target: _blank
          - text: Tidyverse Style Guide
            href: https://style.tidyverse.org/
            target: _blank
      - text: About
        href: about.qmd

format:
  html:
    theme:
      light: [flatly, theme-light.scss]
      dark: [darkly, theme-dark.scss]
    fontsize: 1.0em
    code-copy: true
    code-overflow: wrap

webr: 
  show-startup-message: false
  show-header-message: false
  channel-type: 'post-message'