{
  "hash": "76155e85e91959762e308304f2fb79f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Calibrate Class Probabilities in the ML Workflow\"\ndescription: \"How I add probability calibration to one tidymodels workflow with tailor, and how I decide whether that post-processing step is worth keeping.\"\ndate: 09-25-2026\ncategories: [tidymodels, r]\nimage: preview.png\n---\n\n<!-- Preview image is preview.png, saved from the calibration plot in this post. -->\n\n![](preview.png){.preview-image}\n\n# A passing Brier score can still be a bad probability\n\nI learned these calibration methods at the advanced tidymodels workshop [Max Kuhn](https://max-kuhn.org/){target=\"_blank\"} and [Emil Hvitfeldt](https://emilhvitfeldt.com/){target=\"_blank\"} taught at posit::conf 2025. I came to tidymodels early from caret, and I still see pipelines that stop once [`brier_class()`](https://yardstick.tidymodels.org/reference/brier_class.html){target=\"_blank\"} looks acceptable.\n\nA classifier offers two outputs. The hard class is the label it assigns, for example `class_1` or `class_2`. The classification probability is a number from 0 to 1 for how likely the event is. The event is the positive class, the outcome being counted.\n\nCalibrated means that probability matches the frequency. When the model says 0.7, about 70% of those rows are events.\n\nThat is too early when the probabilities are the product. A tree can rank rows well, land under the 0.25 Brier score I treat as a poor classifier, and still predict 0 and 1 for groups whose event rates are nowhere near 0 and 1. The fix belongs in the same workflow as the recipe and the model.\n\nBrier score is the mean squared error of those probabilities. Lower is better. Always predicting 0.5 scores 0.25. Always predicting the event rate, the share of rows that are events, is the tighter reference, because it knows the base rate and nothing about the predictors.\n\nOn this test set the event rate rounds to 0.25, and the base-rate Brier (that rate times one minus that rate) rounds to 0.188. The scoring chunk prints both numbers again from the test rows.\n\nThe rows are a simulated set from modeldata. The folded chunk loads the packages, simulates 2,000 rows, and splits them twice with `prop = 0.75`, stratified on `class`. The first split holds out the test set. The second holds the calibration set out of the remaining rows.\n\nModel rows fit the tree. Calibration rows are what the post-processor uses to learn a correction from the tree's probabilities to observed event rates. Test rows are only for the final score.\n\nFitting the calibrator on the model rows teaches the wrong mapping. The tree has memorized those rows, so its probabilities there are overconfident, pushed toward 0 and 1. The calibrator pairs those scores with outcomes the tree already fit, and it learns a correction that is too small for new rows.\n\nTest rows have to stay out of both fits. Once they train the calibrator, the test score is no longer an honest estimate of new data.\n\nThe printed table should show model, calibration, and test, and the row counts should sum to 2,000. The workflow in the next section is the part worth copying.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Packages, simulated data, and the three-way split\"}\nlibrary(tidymodels)\nlibrary(probably)\n\ntidymodels_prefer()\ntheme_set(theme_bw())\n\nset.seed(924)\nsim_data <- sim_classification(2000, intercept = -8)\n\nset.seed(925)\ndata_split <- initial_split(sim_data, prop = 0.75, strata = class)\ntrain_data <- training(data_split)\ntest_data <- testing(data_split)\n\nset.seed(926)\ncal_split <- initial_split(train_data, prop = 0.75, strata = class)\nmodel_data <- training(cal_split)\ncalibration_data <- testing(cal_split)\n\ntibble(\n  set = c(\"model\", \"calibration\", \"test\"),\n  rows = c(nrow(model_data), nrow(calibration_data), nrow(test_data))\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 2\n  set          rows\n  <chr>       <int>\n1 model        1124\n2 calibration   376\n3 test          500\n```\n\n\n:::\n:::\n\n\n# The pattern I fit\n\n`workflows` 1.3.0 takes a [tailor](https://tailor.tidymodels.org/){target=\"_blank\"} as the third argument. [`adjust_probability_calibration()`](https://tailor.tidymodels.org/reference/adjust_probability_calibration.html){target=\"_blank\"} is the classification calibrator.\n\nI pass `smooth = FALSE` so the method is a logistic regression (`stats::glm()`), the Platt-style calibrator. The default, `smooth = TRUE`, fits a GAM through `mgcv`. This tree emits only a few distinct probabilities, and a spline is extra machinery I do not need.\n\n[`modeldata::sim_classification()`](https://modeldata.tidymodels.org/reference/sim_classification.html){target=\"_blank\"} ships with the package, so render time does not download anything. `intercept = -8` puts the event (`class_1`, the first factor level, so yardstick's default event) near a quarter of the rows. The three sets in that table are disjoint: model, calibration, and test.\n\n`event_level = \"first\"` in the metrics later tells yardstick to score `.pred_class_1` against that first factor level.\n\nA recipe is the preprocessing plan, run before the model. This one is `step_normalize()` on the numeric predictors. A model spec is the algorithm and its hyperparameters before any fit. The spec below is `decision_tree()` with `tree_depth = 15`, `min_n = 2`, and `cost_complexity = 1e-8`, engine `rpart`, mode classification.\n\nA tailor is a post-processor. It adjusts the model's predictions, and it is trained on its own rows. This tailor is logistic calibration. A workflow is the recipe, the spec, and the tailor bundled into one object.\n\nI want that bundle in production. `predict()` then runs the same steps in the same order: normalize, predict with the tree, then calibrate. One object is how I avoid train/serve skew, where serving drops a step or reimplements it differently.\n\nThe chunk prints the unfitted workflow. Expect the recipe, the tree spec, and a tailor that has not been trained yet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncal_tailor <-\n  tailor() |>\n  adjust_probability_calibration(method = \"logistic\", smooth = FALSE)\n\ntree_spec <-\n  decision_tree(\n    tree_depth = 15,\n    min_n = 2,\n    cost_complexity = 1e-8\n  ) |>\n  set_engine(\"rpart\") |>\n  set_mode(\"classification\")\n\ntree_rec <-\n  recipe(class ~ ., data = train_data) |>\n  step_normalize(all_numeric_predictors())\n\ntree_wflow <- workflow(tree_rec, tree_spec, cal_tailor)\ntree_wflow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n══ Workflow ════════════════════════════════════════════════════════════════════\nPreprocessor: Recipe\nModel: decision_tree()\nPostprocessor: tailor\n\n── Preprocessor ────────────────────────────────────────────────────────────────\n1 Recipe Step\n\n• step_normalize()\n\n── Model ───────────────────────────────────────────────────────────────────────\nDecision Tree Model Specification (classification)\n\nMain Arguments:\n  cost_complexity = 1e-08\n  tree_depth = 15\n  min_n = 2\n\nComputational engine: rpart \n\n\n── Postprocessor ───────────────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNA\nNA\nNA\n```\n\n\n:::\n:::\n\n\nThe three `NA` lines under the postprocessor are the calibrator before it is trained. `fit()` fills them from `data_calibration`.\n\nThe recipe and the model train on `data`. The calibrator trains on predictions from `data_calibration`. Those have to be different rows.\n\nIn-sample probabilities sit closer to the outcome than probabilities on new data. A calibrator fit on the training predictions looks finished when it is not.\n\nThis chunk fits that tree twice and prints nothing. `tree_raw_fit` is the recipe and the tree on `model_data` only. `tree_cal_fit` trains the tailor on `calibration_data`. The next section scores both on the test set, which neither fit has seen.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Fit the same tree with and without the calibrator\"}\ntree_raw_wflow <- workflow(tree_rec, tree_spec)\n\ntree_raw_fit <- fit(tree_raw_wflow, data = model_data)\n\ntree_cal_fit <- fit(\n  tree_wflow,\n  data = model_data,\n  data_calibration = calibration_data\n)\n```\n:::\n\n\n::: {.callout-tip}\n## `fit()` will ask for calibration data\n\nOmitting `data_calibration` is an error: \"The workflow requires `data_calibration` to train but none was supplied.\" I want that error. During resampling, [`tune`](https://tune.tidymodels.org/){target=\"_blank\"} makes the split for me with [`rsample::internal_calibration_split()`](https://rsample.tidymodels.org/reference/internal_calibration_split.html){target=\"_blank\"}. With 5-fold cross-validation, about a fifth of each analysis set is held out to train the calibrator.\n:::\n\n# The score looked fine\n\n`min_n = 2` and a deep tree are deliberate. `tree_depth = 15` lets splits continue for 15 levels, and `cost_complexity = 1e-8` is small enough that rpart keeps them. `min_n = 2` means a node with two rows can still be split, so the leaves are tiny and pure.\n\nThe leaves go pure, so `rpart` reports class probabilities of 0 and 1. A pure leaf is all one class, and rpart stores that class's share of the leaf, which is 0 or 1. That is the failure mode I want on the page. A tuned depth comes later.\n\nThis chunk scores both fits on the test set and hides the printout. It stores accuracy, ROC AUC, Brier score, and a ten-bin `calibration_gap` on `tree_scores`. The next chunk prints that table.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Metrics, including a bin-wise calibration gap\"}\npredict_test <- function(fit) {\n  bind_cols(\n    test_data[\"class\"],\n    predict(fit, test_data, type = \"class\"),\n    predict(fit, test_data, type = \"prob\")\n  )\n}\n\ncalibration_gap <- function(df, n_bins = 10) {\n  breaks <- seq(0, 1, length.out = n_bins + 1)\n  df |>\n    mutate(\n      bin = cut(\n        .pred_class_1,\n        breaks = breaks,\n        include.lowest = TRUE\n      ),\n      event = as.integer(class == \"class_1\")\n    ) |>\n    group_by(bin) |>\n    summarise(\n      n = n(),\n      predicted = mean(.pred_class_1),\n      observed = mean(event),\n      .groups = \"drop\"\n    ) |>\n    summarise(gap = weighted.mean(abs(predicted - observed), n)) |>\n    pull(gap)\n}\n\nscore_fit <- function(fit, label) {\n  df <- predict_test(fit)\n  scored <- bind_rows(\n    accuracy(df, truth = class, estimate = .pred_class),\n    roc_auc(df, truth = class, .pred_class_1, event_level = \"first\"),\n    brier_class(df, truth = class, .pred_class_1, event_level = \"first\")\n  ) |>\n    select(.metric, .estimate) |>\n    pivot_wider(names_from = .metric, values_from = .estimate) |>\n    mutate(calibration_gap = calibration_gap(df), model = label, .before = 1)\n  list(scores = scored, predictions = df)\n}\n\ntest_base_rate <- mean(test_data$class == \"class_1\")\ntest_base_brier <- test_base_rate * (1 - test_base_rate)\nmajority_accuracy <- mean(test_data$class == \"class_2\")\n\ntree_before <- score_fit(tree_raw_fit, \"Tree, before\")\ntree_after <- score_fit(tree_cal_fit, \"Tree, after\")\n\ntree_scores <- bind_rows(tree_before$scores, tree_after$scores) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n:::\n\n\nBrier score is a mean squared error on the probabilities. It punishes a bad ranking and a bad scale at the same time. Predicting 0.5 for every row scores 0.25. Predicting this test set's base rate (0.25) for every row scores 0.188.\n\nThis chunk prints `tree_scores`, rounded to three decimals. I want accuracy and ROC AUC to match across the two rows, and I want Brier score and `calibration_gap` to drop after calibration.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Test-set metrics for the tree\"}\ntree_scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  calibration_gap model        accuracy roc_auc brier_class\n            <dbl> <chr>           <dbl>   <dbl>       <dbl>\n1           0.124 Tree, before    0.876   0.832       0.124\n2           0.016 Tree, after     0.876   0.832       0.104\n```\n\n\n:::\n:::\n\n\nAccuracy is the share of test rows whose hard class matches the truth. It is 0.876 either way, against a majority-class baseline of 0.75. That baseline is the accuracy from ignoring the model and always predicting the majority class, `class_2`.\n\nROC AUC measures ranking only. It asks whether events get higher probabilities than non-events, and it ignores whether those probabilities are on the right scale. ROC AUC stays at 0.832.\n\nThe hard class matches on 500 of 500 test rows. Both calibrated probabilities sit on the same side of 0.5 as the raw 0 and 1.\n\nBrier score moves from 0.124 to 0.104. `calibration_gap` is the average absolute difference between predicted probability and observed event rate, inside ten equal-width bins.\n\nBefore calibration that gap equals the Brier score. Predictions stuck at 0 and 1 make a squared error the same as an absolute error, so the whole 0.124 is miscalibration. After calibration the gap falls to 0.016. What remains in the Brier score is the part a probability adjustment cannot reorder away.\n\nThis chunk lists every distinct predicted probability on the test set, with the row count and the observed event rate. Before calibration I expect only 0 and 1. The `observed` column is the rate those predictions should have matched.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"The only probabilities this tree produces\"}\nprobability_table <- function(df, label) {\n  df |>\n    mutate(event = class == \"class_1\") |>\n    group_by(stage = label, predicted = .pred_class_1) |>\n    summarise(rows = n(), observed = mean(event), .groups = \"drop\") |>\n    mutate(across(c(predicted, observed), \\(x) round(x, 3)))\n}\n\nprobability_summary <- bind_rows(\n  probability_table(tree_before$predictions, \"Before calibration\"),\n  probability_table(tree_after$predictions, \"After calibration\")\n)\n\nprobability_summary\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  stage              predicted  rows observed\n  <chr>                  <dbl> <int>    <dbl>\n1 Before calibration     0       377    0.085\n2 Before calibration     1       123    0.756\n3 After calibration      0.093   377    0.085\n4 After calibration      0.716   123    0.756\n```\n\n\n:::\n:::\n\n\nEvery test row is a 0 or a 1 before calibration. Rows scored 0 are events 0.085 of the time. Rows scored 1 are events 0.756 of the time. After calibration those two piles move to 0.093 and 0.716, next to those same observed rates. Same rows, same order, usable numbers.\n\nThis chunk plots those piles. Each point is one distinct predicted probability, sized by how many test rows share it. The x-axis is the predicted probability of `class_1`. The y-axis is the observed event rate for that point. The gap above used ten equal-width bins. This tree only emits two probabilities, so the honest picture is two points, which is what the plot should show.\n\nThe dashed diagonal is perfect calibration: predicted probability equals the observed rate. A point below the line means the model is overpredicting events (the score is higher than the rate in that group). A point above the line means it is underpredicting. Before calibration the points sit at the edges, off the diagonal. After calibration they should sit close to it.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Calibration plot\"}\ncalibration_points <- bind_rows(\n  tree_before$predictions |> mutate(stage = \"Before calibration\"),\n  tree_after$predictions |> mutate(stage = \"After calibration\")\n) |>\n  mutate(\n    stage = factor(stage, levels = c(\"Before calibration\", \"After calibration\")),\n    event = as.integer(class == \"class_1\")\n  ) |>\n  group_by(stage, predicted = .pred_class_1) |>\n  summarise(rows = n(), observed = mean(event), .groups = \"drop\")\n\ncalibration_plot <-\n  ggplot(calibration_points, aes(predicted, observed)) +\n  geom_abline(slope = 1, intercept = 0, linetype = 2, linewidth = 0.4, color = \"grey35\") +\n  geom_point(aes(size = rows), color = \"#1f4e79\", alpha = 0.9) +\n  facet_wrap(~ stage) +\n  coord_equal(xlim = c(0, 1), ylim = c(0, 1)) +\n  scale_x_continuous(breaks = seq(0, 1, by = 0.25)) +\n  scale_y_continuous(breaks = seq(0, 1, by = 0.25)) +\n  scale_size_area(max_size = 12, breaks = c(100, 300)) +\n  labs(\n    x = \"Predicted probability of class_1\",\n    y = \"Observed event rate\",\n    size = \"Test rows\"\n  ) +\n  theme(legend.position = \"bottom\")\n\nggsave(\n  \"preview.png\",\n  calibration_plot,\n  width = 8,\n  height = 4.6,\n  dpi = 150,\n  bg = \"white\"\n)\n\ncalibration_plot\n```\n\n::: {.cell-output-display}\n![Each point is one distinct predicted probability on the test set. Point size is the number of rows. The dashed line is perfect calibration.](index_files/figure-html/calibration-plot-1.png){fig-alt='Two panels. Before calibration, predicted probabilities sit at 0 and 1 while observed event rates are near 0.08 and 0.76. After calibration, those predictions sit near the diagonal.' width=768}\n:::\n:::\n\n\nThis chunk is the histogram of those same predicted probabilities, drawn as bar height for the row counts. Piles at 0 and at 1 are the overconfidence signal: the model is claiming certainty for large groups of rows. After calibration those bars should move in from the edges, toward the observed event rates. The row counts in the two piles should stay the same, because calibration does not reshuffle which rows are high and which are low.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Histogram of predicted probabilities\"}\nggplot(calibration_points, aes(predicted, rows)) +\n  geom_col(fill = \"#1f4e79\", width = 0.04) +\n  facet_wrap(~ stage) +\n  scale_x_continuous(limits = c(0, 1), breaks = seq(0, 1, by = 0.25)) +\n  labs(x = \"Predicted probability of class_1\", y = \"Test rows\")\n```\n\n::: {.cell-output-display}\n![Calibration moves the two spikes toward the observed event rates. It does not invent a new ranking.](index_files/figure-html/probability-histogram-1.png){fig-alt='Histograms of predicted class_1 probabilities. Before calibration every value is 0 or 1. After calibration those spikes move inward.' width=768}\n:::\n:::\n\n\n[`probably::cal_plot_windowed()`](https://probably.tidymodels.org/reference/cal_plot_windowed.html){target=\"_blank\"} is what I use when a model produces a spread of probabilities (it is the plot from the workshop). Here it would draw a smooth curve through two spikes and invent probabilities the tree never made. The binned plot matches the model.\n\n# When I leave the calibrator out\n\nSame split, same logistic calibrator, a logistic regression instead of the tree.\n\nThis chunk fits that logistic regression with and without the calibrator, and it prints nothing. A logistic regression already fits probabilities with a logistic curve, so I expect little systematic bend left for the tailor to remove. The next table is the check.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Logistic regression, before and after the same calibrator\"}\nlogit_spec <- logistic_reg()\nlogit_raw_fit <- fit(workflow(tree_rec, logit_spec), data = model_data)\nlogit_cal_fit <- fit(\n  workflow(tree_rec, logit_spec, cal_tailor),\n  data = model_data,\n  data_calibration = calibration_data\n)\n\nlogit_before <- score_fit(logit_raw_fit, \"Logistic regression, before\")\nlogit_after <- score_fit(logit_cal_fit, \"Logistic regression, after\")\n\nlogit_scores <- bind_rows(logit_before$scores, logit_after$scores) |>\n  mutate(across(where(is.numeric), \\(x) round(x, 3)))\n```\n:::\n\n\nThis chunk prints the same four metrics for the logistic regression. I am looking for a Brier score and a calibration gap that do not improve, and for an ROC AUC that stays put.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Test-set metrics for the logistic regression\"}\nlogit_scores\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  calibration_gap model                       accuracy roc_auc brier_class\n            <dbl> <chr>                          <dbl>   <dbl>       <dbl>\n1           0.038 Logistic regression, before    0.814    0.82       0.132\n2           0.05  Logistic regression, after     0.826    0.82       0.134\n```\n\n\n:::\n:::\n\n\nI recommend keeping the calibrator when the probability histogram is piled on the edges, or when `calibration_gap` is large next to the Brier score. I take it out when the model already speaks in probabilities and the gap is small. This logistic regression is that second case. Brier goes from 0.132 to 0.134, a small step in the wrong direction, and the calibration gap does not improve. A second logistic fit on a few hundred calibration rows has no systematic bend to remove.\n\nI do not calibrate by default. This model is already calibrated. The extra fit adds variance, and the calibration split is data the model never sees, for little or no gain.\n\nA few rules I use on top of that plot:\n\n- ROC AUC is unchanged for both models here. Logistic calibration is a monotonic transform of the predicted probability only, so the ranking of rows is unchanged. If I only need a ranking, I skip it.\n- Accuracy stayed flat for the tree. For the logistic regression it moved from 0.814 to 0.826, because a few probabilities crossed 0.5. A hard label is a blunt summary of a probability.\n- Thresholds do not repair calibration. [`adjust_probability_threshold()`](https://tailor.tidymodels.org/reference/adjust_probability_threshold.html){target=\"_blank\"} changes the hard class, and it leaves Brier score and ROC AUC alone. Put it after calibration.\n- Isotonic regression (`method = \"isotonic\"`) is the other base-R option, and it is a step function. Beta calibration is available too, through the [betacal](https://cran.r-project.org/package=betacal){target=\"_blank\"} package. I start with logistic, then look at the plot.\n- A calibration set with zero or one row makes tailor switch the method to `\"none\"`. I keep a few hundred events in that split when I can.\n\n::: {.callout-tip}\n## Calibrate, then threshold\n\ntailor stops if a threshold or an equivocal zone is declared before the probability update. Those steps rewrite the hard class. On this tree the calibrated probabilities sit near 0.09 and 0.72, so any cutoff between them assigns the same class the raw 0 and 1 did.\n\nThe chunk builds the tailor in the wrong order and catches the error. The message should say that adjustments which change the hard class have to come after the probability update.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"The error if the threshold comes first\"}\nthreshold_first <- tryCatch(\n  tailor() |>\n    adjust_probability_threshold(threshold = 0.2) |>\n    adjust_probability_calibration(method = \"logistic\", smooth = FALSE),\n  error = function(e) conditionMessage(e)\n)\n\nthreshold_first\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Adjustments that change the hard class predictions must come after\\nadjustments that update the class probability estimates.\"\n```\n\n\n:::\n:::\n\n:::\n\n# One workflow, with the tune included\n\nThe depth-15 tree was a demonstration of pure leaves. I would not ship it only because the calibrator patched the scale. With the tailor already attached, `tune_grid()` scores candidates after post-processing, which is the comparison I want. Three depths, five folds, on the training data. tune holds out the calibration rows inside each analysis set, so this call does not take `data_calibration`.\n\nThe gain is a depth chosen for the probabilities I will actually ship. Each resample fits its own calibrator on rows held out from that resample's model fit, so the tree's training rows do not leak into the calibration.\n\nThis chunk tunes `tree_depth` over 4, 8, and 15, with `min_n` still 2 and `cost_complexity` still `1e-8`. The table is mean Brier score and ROC AUC across folds, plus the standard error. I take the lowest Brier score.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Tune tree depth with the calibrator attached\"}\nset.seed(927)\ndepth_folds <- vfold_cv(train_data, v = 5, strata = class)\n\ndepth_spec <-\n  decision_tree(\n    tree_depth = tune(),\n    min_n = 2,\n    cost_complexity = 1e-8\n  ) |>\n  set_engine(\"rpart\") |>\n  set_mode(\"classification\")\n\ndepth_wflow <- workflow(tree_rec, depth_spec, cal_tailor)\n\nset.seed(12)\ndepth_res <- tune_grid(\n  depth_wflow,\n  resamples = depth_folds,\n  grid = tibble(tree_depth = c(4L, 8L, 15L)),\n  metrics = metric_set(brier_class, roc_auc)\n)\n\ndepth_metrics <-\n  collect_metrics(depth_res) |>\n  select(tree_depth, .metric, mean, std_err) |>\n  arrange(.metric, tree_depth) |>\n  mutate(across(c(mean, std_err), \\(x) round(x, 3)))\n\ndepth_metrics\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 4\n  tree_depth .metric      mean std_err\n       <int> <chr>       <dbl>   <dbl>\n1          4 brier_class 0.089   0.003\n2          8 brier_class 0.101   0.003\n3         15 brier_class 0.106   0.004\n4          4 roc_auc     0.841   0.006\n5          8 roc_auc     0.837   0.014\n6         15 roc_auc     0.833   0.008\n```\n\n\n:::\n:::\n\n\nThis chunk locks in the best depth with `select_best()` and `finalize_workflow()`, then fits once on `model_data` and `calibration_data`. I want `tree_depth` filled in on the spec. I want `extract_postprocessor()` to show a trained calibrator where the earlier printout had `NA`.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Finalize the best depth and fit one workflow\"}\nbest_depth <- select_best(depth_res, metric = \"brier_class\")\nbest_depth\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  tree_depth .config        \n       <int> <chr>          \n1          4 pre0_mod1_post0\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Finalize the best depth and fit one workflow\"}\nfinal_wflow <- finalize_workflow(depth_wflow, best_depth)\nfinal_wflow\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n══ Workflow ════════════════════════════════════════════════════════════════════\nPreprocessor: Recipe\nModel: decision_tree()\nPostprocessor: tailor\n\n── Preprocessor ────────────────────────────────────────────────────────────────\n1 Recipe Step\n\n• step_normalize()\n\n── Model ───────────────────────────────────────────────────────────────────────\nDecision Tree Model Specification (classification)\n\nMain Arguments:\n  cost_complexity = 1e-08\n  tree_depth = 4\n  min_n = 2\n\nComputational engine: rpart \n\n\n── Postprocessor ───────────────────────────────────────────────────────────────\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNA\nNA\nNA\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Finalize the best depth and fit one workflow\"}\nfinal_fit <- fit(\n  final_wflow,\n  data = model_data,\n  data_calibration = calibration_data\n)\n\nextract_postprocessor(final_fit)\n```\n:::\n\n\nDepth 4 wins on resampled Brier score. Calibration did not promote the overgrown tree. I still keep the calibrator in `final_wflow`: the object that gets predicted from runs the recipe, the tree, and the logistic adjustment, in that order. `predict(final_fit, new_data, type = \"prob\")` is the whole path.\n\n[orbital](https://orbital.tidymodels.org/articles/supported-models.html){target=\"_blank\"} translates a fitted workflow into SQL, so predictions can run inside the database without R. Version 0.7.0 covers this `step_normalize()` recipe and this `decision_tree(engine = \"rpart\")` model, including class and probability predictions.\n\n`adjust_probability_calibration()` is outside that list (orbital's tailor support is `adjust_probability_threshold()`, `adjust_equivocal_zone()`, `adjust_numeric_range()`, and `adjust_predictions_custom()`). The calibration step is what orbital cannot translate yet, so this calibrated workflow stays in R.\n\n# Learn more\n\n- [tailor](https://tailor.tidymodels.org/){target=\"_blank\"}, by Simon Couch, Hannah Frick, Emil Hvitfeldt, and Max Kuhn. The [calibration reference](https://tailor.tidymodels.org/reference/adjust_probability_calibration.html){target=\"_blank\"} documents logistic, multinomial, beta, and isotonic methods.\n- [`add_tailor()`](https://workflows.tidymodels.org/reference/add_tailor.html){target=\"_blank\"} and [`fit.workflow()`](https://workflows.tidymodels.org/reference/fit-workflow.html){target=\"_blank\"} on `data` versus `data_calibration`. workflows 1.3.0 added the postprocessor stage.\n- [tune 2.0.0](https://opensource.posit.co/blog/2025-11-05_tune-2/){target=\"_blank\"} tunes tailor parameters and replaced foreach with future and mirai. tune 2.1.0 restored the submodel trick for the model and for the calibration model.\n- [probably](https://probably.tidymodels.org/){target=\"_blank\"} supplies the calibration estimators and the `cal_plot_*()` family. yardstick 1.4.0 gave `brier_class()` an `event_level` argument. It still does not ship a standalone calibration metric, which is why the bin gap above is computed in the post.\n- [Calibration in Applied Machine Learning for Tabular Data](https://aml4td.org/chapters/cls-metrics.html#sec-cls-calibration){target=\"_blank\"}, Max Kuhn's chapter on the same idea.\n- [orbital's supported models, recipes, and tailor steps](https://orbital.tidymodels.org/articles/supported-models.html){target=\"_blank\"}.\n\nThe pattern I want in production is the fitted `final_wflow`: preprocess, model, then calibrate, scored after the adjustment. If your probability histogram is already a smooth ramp along the diagonal, delete the tailor and keep the simpler object.\n\nWhen an agent writes the model for me, I check:\n\n- Calibration rows that were not used to fit the model, and a test set that was used for neither.\n- A calibration plot, points against the diagonal. A metric on its own can still hide probabilities stuck at 0 and 1.\n- Brier score next to the base-rate reference (0.188 on this test set) and next to the 0.25 from always predicting 0.5.\n- Post-processing order: calibrate, then set a threshold. A cutoff rewrites the hard class and leaves the probabilities alone.\n- One workflow object for `predict()`, so the recipe, the model, and the calibrator run in that order.\n\nHappy Thursday, and happy coding!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}